name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: "font-noto font-noto-cjk font-noto-cjk-extra"
          extra_fonts: |
            ./assets/fonts/lxgw-wenkai-v1.240/*.ttf
          root_file: ./docs/notes/main.tex
#         working_directory: ./docs/notes
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          #work_in_root_file_dir: true

      - name: Consolidate pdfs
        run: mkdir -p build/ && cp docs/notes/main.pdf build/

      - name: Upload pdf artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_results
          path: build
          retention-days: 1

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pdfs
          folder: build
          ssh-key: "${{ secrets.DEPLOY_KEY }}"

